### ISSUE TITLE
Chapter14.3.2: the class is different for this repository and the book

### ISSUE THREAD

**Issue by yinm** [eddyerburgh/vue-hackernews#3]
In Chapter14.3.2, the class is different for this repository and the book.

In this repository

https://github.com/eddyerburgh/vue-hackernews/blob/789c77c21b9bc19bda40d17d1a6b91e1b58c19d3/e2e/specs/journeys.js#L5

In the book, the class here is `.news-item`.

I think the class in the book is typo because there isn't `.news-item` class in source code.
What do you think?

**Comment by yinm** [comment]
@eddyerburgh

**Comment by eddyerburgh** [comment]
Thanks for alerting me of this. I've updated the source code to reflect the book, since the book has now been printed. It was my intention to refactor the class to item, but I forgot to update the book.

**Comment by yinm** [comment]
Thanks for reply and updating the source code. 😄
