### ISSUE TITLE
Chapter 2 - Test suite failed to run - Jest encountered an unexpected token import

### ISSUE THREAD

**Issue by farahriz** [eddyerburgh/vue-hackernews#4]
## Problem
_Note: This problem was resolved myself, but I am raising an issue as a reference for anyone else who is attempting to follow along and in case the issue was not limited to my machine/reflects something that needs to be noted in the [errata](https://manning-content.s3.amazonaws.com/download/b/921f670-42b2-4adb-ab94-70efb8bbf428/Yerburgh_Testingue.jsApplications_Err1.html)._

_As another person pointed out in a different issue, much pain can be avoided by checking out straight to Chapter 3 and then running `$npm install`_ 

I was following along with a hard copy of the Manning book and despite fixing the versions of jest and babel-jest installed to match the errata, I kept encountering a problem importing vue components whenever I ran  `$npm run test:unit` . It seems that babel was not transpiling the 'import'.

` **Test suite failed to run**

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    <directory>/src/components/__tests__/Item.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Vue from "vue";
                                                                                             ^^^^^^

    SyntaxError: Unexpected token import

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)`

## Details and steps for reproduction
OS: Windows 10
node: v10.15.3
npm: v6.4.1
Installation of packages via npm
"devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.15",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.16",
    "@vue/cli-service": "^3.0.0-beta.15",
    "@vue/eslint-config-standard": "^3.0.0-beta.16",
    "babel-core": "^7.0.0-bridge.0",
    "babel-jest": "^23.0.1",
    "cross-env": "^5.2.0",
    "jest": "^23.6.0",
    "vue-jest": "^2.6.0",
    "vue-template-compiler": "^2.5.16"
  } 

1. Clone github repo
2. Checkout to chapter-2
3. Follow instructions until page 34 of book

## Solution
After much googling, I found someone else with [a similar problem](https://medium.com/@samuelpouyt/how-to-solve-vue-error-with-jest-e8e9ff7d0cec)

Following the advice in that article amending the package.json file seemed to fix the issue as below. 
`
"jest": {
    "transform": {
      "^.+\\.vue$": "vue-jest",
      "^.+\\.(js|jsx)?$": "<rootDir>/node_modules/babel-jest"
    }
  }
`

The conceptual explanations in the book are very clear and enjoyable, especially for a beginner like me.
Hope I can help someone else get through Chapter 2 to enjoy the rest of it (and hope this might bring other possible issues to light.)

**Comment by DCToddM** [comment]
Thanks you farahriz for this.  I've been dealing with this problem for the past few hours trying to fix this exact problem.

**Comment by eddyerburgh** [comment]
I'm very sorry to everyone who has dealt with this problem, I've tried to fix this by pinning versions in the errata: https://manning-content.s3.amazonaws.com/download/b/921f670-42b2-4adb-ab94-70efb8bbf428/Yerburgh_Testingue.jsApplications_Err1.html. Can you let me know if you have problems following the errata?
