### ISSUE TITLE
Chapter 4: Test suite failed due to not being able to read instance property of undefined

### ISSUE THREAD

**Issue by BorisAng** [eddyerburgh/vue-hackernews#5]
Going through Chapter 4 and more specifically the part where before mounting the `start()` method is called on the instance property `$bar`. 

When I run the test I get the following error, hence all other test inside `ItemList.spec` fail

![image](https://user-images.githubusercontent.com/24811561/64703853-1e9feb00-d4a5-11e9-923c-e3fbad34e3fc.png)

I have added `$bar` as an instance to the prototype as explained in Listing 4.15 (page 74)

@eddyerburgh Any help will be appreciated, let me know if more info is needed

**Comment by eddyerburgh** [comment]
Hi. You need to use the `mocks` option in your tests to ensure $bar is defined. Updating the code according to section 4.4 should solve this issue.

**Comment by BorisAng** [comment]
@eddyerburgh thanks for the prompt reply. 

I might be wrong but I'm already using the ```mocks``` option inside the test, as in: 

```
  it('should call $bar.start on load', () => {
    const $bar = {
      start: jest.fn(),
      finish: () => {}
    }
    shallowMount(ItemList, { mocks: $bar })
    expect($bar.start).toHaveBeenCalledTimes(1)
  })
```
Inside the ```ItemList``` component, I have added the ```beforeMount``` hook, i.e.
```
export default {
  components: {
    Item
  },
  beforeMount() {
    // console.log(this.$bar.start)
    this.$bar.start()
    // this.loadItems()
  },
  data () {
    return {
      displayItems: []
    }
  },
  methods: {
    loadItems() {
        this.$bar.start()
        fetchListData('top').then(items => {
            this.displayItems = items
            this.$bar.finish()
        })
    }
  }
}
```
Uncommenting ```this.loadsItems()``` and removing ```this.$bar.start()``` causes pretty much the same issue

**Comment by eddyerburgh** [comment]
`mocks` should be an object containing `$bar`:

```js
  it('should call $bar.start on load', () => {
    const $bar = {
      start: jest.fn(),
      finish: () => {}
    }
    shallowMount(ItemList, { mocks: { $bar } })
    expect($bar.start).toHaveBeenCalledTimes(1)
  })
```

**Comment by BorisAng** [comment]
@eddyerburgh , I've been staring at this way too much to miss that ```mocks``` wasn't an object in my code. Thank you!
